Guanyu/feature/spring and lock
jianwei-sun/gtfo pull request #70
Opened 2024-03-25 03:05 UTC by gychen98

Good news! Now everything works well in simulation. Thank you!

I am not sure why we need to update pointmassfirstorder. it seems that if we consider it as a low pass filter, the dc gain will contain the stiffness, and the time constant is a combination of both the damping and stiffness.
$$
X = \frac{Force/k}{1+\frac{d}{k}s}
$$
where k is the stiffness, d is damping, and $\frac{d}{k}$ is the time constant.

2024-03-25 20:38 UTC, jianwei-sun requested changes
For `PointMassFirstOrder`, I just meant the `SetStateTransitionMatrices` should just set `Base::C_discrete_` to zero just to be extra clear.

I think the unit tests are still not building yet - could you take a look?

2024-03-26 01:02 UTC, gychen98 commented
Hi Jianwei, 

I tried to create a workflow in the actions section for the unit test. Do you have any recommendations of those workflows like c/c++ with make or MSbased projects?

2024-03-26 03:54 UTC, jianwei-sun commented
Ah, you don't need to worry about any of that. Please follow the instructions at the Contributing section (near the end) of the README.md.

2024-03-26 08:48 UTC, gychen98 commented
I cmake with the prefix path to mujoco and osqp. It can find osqp config files. However, for mujoco, it shows that "CMake Warning at CMakeLists.txt:46 (find_package):
  Could not find a configuration file for package "mujoco" that is compatible
  with requested version "2.3.1".

  The following configuration files were considered but not accepted:

    E:/PhD_Research/Two_arm_exo/exoul8/lib/mujoco-2.3.1/build/mujocoConfig.cmake, version: 2.3.1 (32bit)". The version is 2.3.1 as shown here, but it said it cannot find the package that is compatible with 2.3.1.

2024-03-27 07:07 UTC, gychen98 commented
It seems like after I broadcast the affine terms, the barrier, rectangular, and circular constraints tests cannot pass. The mujoco-related tests can neither pass even in the main branch no matter whether there is the affine term.

2024-03-28 20:21 UTC, jianwei-sun approved these changes
Looks good, thanks for making the changes!

2024-03-29 21:45 UTC, merged